name: CI-CD Pipeline

env:
  DOTNET_VERSION: "9.0.x"  

on:
  push:
    branches: [main]       
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"    
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options: [chrome, firefox, edge]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      dotnet-version: ${{ steps.setup-dotnet.outputs.dotnet-version }}
    steps:
      - name: Setup .NET
        id: setup-dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

  api-tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout API repo
        uses: actions/checkout@v4
        with:
          repository: AlibekNamazbayev/APIAutomation
          token: ${{ secrets.GITHUB_TOKEN }}
          path: api-repo

      - name: Build and test API
        run: |
          dotnet build ApiTestSolution.sln --configuration Release
          dotnet test ApiTest.Tests/ApiTest.Tests.csproj --logger trx
        working-directory: ./api-repo

      - name: Upload API results
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: ./api-repo/**/*.trx

  ui-tests:
    runs-on: ubuntu-latest
    needs: 
      - setup
      - api-tests
    if: always()  
    steps:
      - name: Checkout UI repo
        uses: actions/checkout@v4
        with:
          repository: AlibekNamazbayev/.NET-Web-UI-Test-Automation-Tools-Part-2
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ui-repo

      - name: Build and test UI
        run: |
          dotnet build SeleniumTests.csproj --configuration Release
          dotnet test SeleniumTests.csproj --logger trx --browser ${{ github.event.inputs.browser }}
        working-directory: ./ui-repo

      - name: Upload UI results
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: ./ui-repo/**/*.trx

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: ui-screenshots
          path: ./ui-repo/**/*.png