name: CI-CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"  # Ежедневно в 00:00 UTC
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options: [chrome, firefox, edge]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    name: API Tests
    # Если API тесты падают, UI тесты всё равно выполнятся
    continue-on-error: true
    steps:
      - name: Checkout API repository
        uses: actions/checkout@v4
        with:
          repository: 'AlibekNamazbayev/APIAutomation'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: api-repo

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore, Build and Run API Tests
        run: |
          dotnet restore ApiTestSolution.sln
          dotnet build ApiTestSolution.sln --configuration Release
          dotnet test APITest.Tests/ApiTest.Tests.csproj --logger "trx"
        working-directory: ./api-repo

      - name: Upload API Test Results
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: '**/*.trx'

  ui-tests:
    runs-on: ubuntu-latest
    name: UI Tests
    needs: api-tests
    if: always()
    steps:
      - name: Checkout UI repository
        uses: actions/checkout@v4
        with:
          repository: 'AlibekNamazbayev/.NET-Web-UI-Test-Automation-Tools-Part-2'
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ui-repo

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore UI Solution
        run: dotnet restore EpamAutomationSolution.sln
        working-directory: ./ui-repo

      - name: Build Selenium Tests
        run: dotnet build SeleniumTests.csproj --configuration Release /p:GenerateAssemblyInfo=false
        working-directory: ./ui-repo

      - name: Run UI Tests
        env:
          BROWSER: ${{ github.event.inputs.browser }}
        run: dotnet test SeleniumTests.csproj --logger "trx"
        working-directory: ./ui-repo

      - name: Upload UI Test Results
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: '**/*.trx'

      - name: Upload Screenshots and Logs
        uses: actions/upload-artifact@v4
        with:
          name: ui-screenshots
          path: '**/*.png'
