name: CI-CD Pipeline

env:
  DOTNET_VERSION: "9.0.301" 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options: [chrome, firefox, edge]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout API repo
        uses: actions/checkout@v4
        with:
          repository: AlibekNamazbayev/APIAutomation
          token: ${{ secrets.GITHUB_TOKEN }}
          path: api-repo

      - name: Install .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Verify .NET version
        run: dotnet --version

      - name: Execute API tests
        run: dotnet test ApiTestSolution.sln --configuration Release --logger trx
        working-directory: ./api-repo

  ui-tests:
    runs-on: ubuntu-latest
    needs: api-tests
    if: always()
    steps:
      - name: Checkout UI repo
        uses: actions/checkout@v4
        with:
          repository: AlibekNamazbayev/.NET-Web-UI-Test-Automation-Tools-Part-2
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ui-repo

      - name: Install .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Verify .NET version
        run: dotnet --version

      - name: Execute UI tests
        run: |
          export BROWSER=${{ github.event.inputs.browser }}
          dotnet test SeleniumTests.csproj --configuration Release --logger trx
        working-directory: ./ui-repo