name: CI-CD Pipeline

on:
  push:
    branches: [test-branch]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options: [chrome, firefox, edge]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    name: API Tests
    steps:
      - name: Checkout API repo
        uses: actions/checkout@v4
        with:
          repository: AlibekNamazbayev/APIAutomation
          token: ${{ secrets.GITHUB_TOKEN }}
          path: api-repo

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ApiTestSolution.sln
        working-directory: ./api-repo

      - name: Build solution
        run: dotnet build ApiTestSolution.sln --configuration Release
        working-directory: ./api-repo

      - name: Run API tests
        run: dotnet test ApiTest.Tests/ApiTest.Tests.csproj --logger trx
        working-directory: ./api-repo

      - name: Upload API results
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: ./api-repo/**/*.trx

  ui-tests:
    runs-on: ubuntu-latest
    name: UI Tests
    needs: api-tests
    steps:
      - name: Checkout UI repo
        uses: actions/checkout@v4
        with:
          repository: AlibekNamazbayev/.NET-Web-UI-Test-Automation-Tools-Part-2
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ui-repo

      - name: Debug UI structure
        run: ls -R
        working-directory: ./ui-repo

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore UI dependencies
        run: dotnet restore EpamAutomationSolution.sln
        working-directory: ./ui-repo

      - name: Build UI solution
        run: dotnet build EpamAutomationSolution.sln --configuration Release
        working-directory: ./ui-repo

      - name: Run UI tests
        run: dotnet test EpamAutomation.Tests/EpamAutomation.Tests.csproj --logger trx --browser ${{ github.event.inputs.browser }}
        working-directory: ./ui-repo

      - name: Upload UI results
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: ./ui-repo/**/*.trx

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: ui-screenshots
          path: 
            - ./ui-repo/**/*.png
            - ./ui-repo/**/*.log