name: CI-CD Pipeline

on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"  # Запуск по расписанию (каждый день в 00:00)
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options:
          - chrome
          - firefox
          - edge

jobs:
  api-tests:
    runs-on: ubuntu-latest
    name: Run API Tests
    steps:
      - name: Checkout API repository
        uses: actions/checkout@v2
        with:
          repository: 'AlibekNamazbayev/APIAutomation'
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore APIAutomation.sln

      - name: Build API project
        run: dotnet build APIAutomation.sln --configuration Release

      - name: Run API tests
        run: dotnet test APITest.Tests/ApiTest.Tests.csproj --logger "trx"

      - name: Upload API test results
        uses: actions/upload-artifact@v2
        with:
          name: api-test-results
          path: **/*.trx

  ui-tests:
    runs-on: ubuntu-latest
    name: Run UI Tests
    needs: api-tests
    steps:
      - name: Checkout UI repository
        uses: actions/checkout@v2
        with:
          repository: 'AlibekNamazbayev/.NET-Web-UI-Test-Automation-Tools-Part-2'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore UIAutomation.sln

      - name: Build UI project
        run: dotnet build UIAutomation.sln --configuration Release

      - name: Run UI tests
        run: |
          dotnet test UIAutomation.Tests/UIAutomation.Tests.csproj --browser ${{ github.event.inputs.browser }} --logger "trx"

      - name: Upload UI test results
        uses: actions/upload-artifact@v2
        with:
          name: ui-test-results
          path: **/*.trx

      - name: Upload screenshots and logs
        uses: actions/upload-artifact@v2
        with:
          name: ui-screenshots
          path: '**/*.png'
