api-tests:
  runs-on: ubuntu-latest
  name: Run API Tests
  steps:
    - name: Checkout API repository
      uses: actions/checkout@v3
      with:
        repository: 'AlibekNamazbayev/APIAutomation'
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: List directory structure (debug)
      run: ls -R

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Find solution file
      id: find-sln
      run: |
        SOLUTION_FILE=$(find . -name "*.sln" | head -n 1)
        echo "SOLUTION_FILE=${SOLUTION_FILE}" >> $GITHUB_OUTPUT
        if [ -z "$SOLUTION_FILE" ]; then
          echo "Error: No solution file found in repository"
          exit 1
        fi

    - name: Restore dependencies
      run: dotnet restore ${{ steps.find-sln.outputs.SOLUTION_FILE }}

    - name: Build API project
      run: dotnet build ${{ steps.find-sln.outputs.SOLUTION_FILE }} --configuration Release

    - name: Find test project
      id: find-test-proj
      run: |
        TEST_PROJECT=$(find . -name "*Tests.csproj" | head -n 1)
        echo "TEST_PROJECT=${TEST_PROJECT}" >> $GITHUB_OUTPUT
        if [ -z "$TEST_PROJECT" ]; then
          echo "Error: No test project found in repository"
          exit 1
        fi

    - name: Run API tests
      run: dotnet test ${{ steps.find-test-proj.outputs.TEST_PROJECT }} --logger "trx"

    - name: Upload API test results
      uses: actions/upload-artifact@v4
      with:
        name: api-test-results
        path: '**/*.trx'