name: CI-CD Pipeline

env:
  DOTNET_VERSION: "9.0.x"  

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options: [chrome, firefox, edge]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout API repo
        uses: actions/checkout@v4
        with:
          repository: AlibekNamazbayev/APIAutomation
          token: ${{ secrets.GITHUB_TOKEN }}
          path: api-repo

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
         
          dotnet-quality: 'preview'

      - name: Verify .NET version
        run: dotnet --info

  ui-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          dotnet-quality: 'preview'