name: CI-CD Pipeline

env:
  DOTNET_VERSION: "8.0.301" 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options: [chrome, firefox, edge]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Verify .NET SDK
        run: dotnet --info

  api-tests:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout API repo
        uses: actions/checkout@v4
        with:
          repository: AlibekNamazbayev/APIAutomation
          token: ${{ secrets.GITHUB_TOKEN }}
          path: api-repo

      - name: Build and Test API
        run: |
          dotnet build ApiTestSolution.sln --configuration Release
          dotnet test ApiTest.Tests/ApiTest.Tests.csproj --logger trx
        working-directory: ./api-repo

  ui-tests:
    runs-on: ubuntu-latest
    needs: 
      - setup
      - api-tests
    if: always()
    steps:
      - name: Checkout UI repo
        uses: actions/checkout@v4
        with:
          repository: AlibekNamazbayev/.NET-Web-UI-Test-Automation-Tools-Part-2
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ui-repo

      - name: Build and Test UI
        run: |
          dotnet test SeleniumTests.csproj \
            --configuration Release \
            --logger "trx;LogFileName=ui-test-results.trx" \
            --filter "TestCategory=Browser&Browser=${{ github.event.inputs.browser }}"
        working-directory: ./ui-repo