name: CI-CD Pipeline

on:
  push:
    branches: [test-branch]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      browser:
        description: 'Select browser for UI tests'
        required: true
        default: 'chrome'
        type: choice
        options: [chrome, firefox, edge]

jobs:
  api-tests:
    runs-on: ubuntu-latest
    name: API Tests
    steps:
      - name: Checkout API repo
        uses: actions/checkout@v4
        with:
          repository: AlibekNamazbayev/APIAutomation
          token: ${{ secrets.GITHUB_TOKEN }}
          path: api-repo

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            9.0.x
            8.0.x  

      - name: Restore dependencies
        run: dotnet restore ApiTestSolution.sln
        working-directory: ./api-repo

  ui-tests:
    runs-on: ubuntu-latest
    name: UI Tests
    needs: api-tests
    steps:
      - name: Checkout UI repo
        uses: actions/checkout@v4
        with:
          repository: AlibekNamazbayev/.NET-Web-UI-Test-Automation-Tools-Part-2
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ui-repo

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            9.0.203  
            8.0.301  

      - name: Verify .NET version
        run: dotnet --info

      - name: Clean project
        run: dotnet clean SeleniumTests.csproj --framework net9.0
        working-directory: ./ui-repo

      - name: Restore dependencies
        run: dotnet restore SeleniumTests.csproj
        working-directory: ./ui-repo

      - name: Build project
        run: dotnet build SeleniumTests.csproj --configuration Release --no-restore
        working-directory: ./ui-repo