jobs:
  api-tests:
    runs-on: ubuntu-latest
    name: Run API Tests
    steps:
      - name: Checkout API repository
        uses: actions/checkout@v3
        with:
          repository: 'AlibekNamazbayev/APIAutomation'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore ApiTestSolution.sln

      - name: Build API project
        run: dotnet build ApiTestSolution.sln --configuration Release

      - name: Run API tests
        run: dotnet test ApiTest.Tests/ApiTest.Tests.csproj --logger "trx"

      - name: Upload API test results
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: '**/*.trx'